"""
server/app.py
=============
FastAPI HTTP server that wraps the DataCleaningEnvironment.

Endpoints (all required by OpenEnv spec):
  GET  /health    → health check (must return 200)
  POST /reset     → start a new episode
  POST /step      → submit an action (cleaned data)
  GET  /state     → get episode metadata
  GET  /schema    → action, observation, and state schemas (required by validator)
  GET  /metadata  → environment name and description (required by validator)
  GET  /openapi.json → OpenAPI spec with version (required by validator)
  GET  /docs      → interactive API docs (auto-generated by FastAPI)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import Any, Dict

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from models import DataCleaningAction
from server.environment import DataCleaningEnvironment

# ─────────────────────────────────────────────────────────────────────────────
# Application setup
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Data Cleaning Agent Environment",
    description=(
        "An OpenEnv-compliant environment where AI agents learn to clean messy "
        "tabular datasets. Three tasks: column name fixing (easy), missing value "
        "handling (medium), and full data reconstruction (hard)."
    ),
    version="1.0.0",
    openapi_url="/openapi.json",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Allow all origins — required for HuggingFace Spaces and external clients
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# One global environment instance per server process
# (stateful — holds current episode state)
env = DataCleaningEnvironment()


# ─────────────────────────────────────────────────────────────────────────────
# Core OpenEnv endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health", summary="Health check")
def health_check() -> Dict[str, str]:
    """
    Returns 200 OK when the server is running.
    The OpenEnv validator pings this endpoint first.
    """
    return {"status": "healthy"}


@app.post("/reset", summary="Start a new episode")
def reset(
    task_id: int = Query(
        default=1,
        ge=1,
        le=3,
        description="Task ID: 1=Easy, 2=Medium, 3=Hard"
    )
) -> Dict[str, Any]:
    """
    Start a new episode.

    Query parameter:
        task_id: 1 (column cleaning, easy),
                 2 (missing values + dedup, medium),
                 3 (full reconstruction, hard)

    Returns the initial observation containing the dirty dataset.
    """
    try:
        obs = env.reset(task_id=task_id)
        return {
            "observation": obs.model_dump(),
            "reward": 0.0,
            "done": False,
            "info": {"episode_id": env._episode_id, "task_id": task_id},
        }
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.post("/step", summary="Submit cleaned data")
def step(action: DataCleaningAction) -> Dict[str, Any]:
    """
    The agent submits its cleaned version of the dataset.

    Request body (JSON):
        task_id      : int (1, 2, or 3)
        cleaned_data : list of row dicts
        metadata     : dict (optional)

    Returns the grader's evaluation: score, feedback, and next observation.
    """
    try:
        obs, reward, done, info = env.step(action)
        return {
            "observation": obs.model_dump(),
            "reward": reward,
            "done": done,
            "info": info,
        }
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Internal error: {exc}")


@app.get("/state", summary="Get episode state")
def get_state() -> Dict[str, Any]:
    """
    Returns episode-level metadata: episode_id, step_count, task_id, best_score.
    Safe to call before reset() — returns default values if no episode is active.
    """
    return env.state().model_dump()


# ─────────────────────────────────────────────────────────────────────────────
# OpenEnv validator required endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/schema", summary="Action, observation and state schemas")
def get_schema() -> Dict[str, Any]:
    """
    Returns the action, observation, and state schemas.
    Required by OpenEnv validator.
    """
    return {
        "action": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 3,
                    "description": "Task ID: 1=Easy, 2=Medium, 3=Hard"
                },
                "cleaned_data": {
                    "type": "array",
                    "items": {"type": "object"},
                    "description": "The cleaned dataset as a list of row dicts"
                },
                "metadata": {
                    "type": "object",
                    "description": "Optional metadata"
                }
            },
            "required": ["task_id", "cleaned_data"]
        },
        "observation": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "Current task ID"
                },
                "task_description": {
                    "type": "string",
                    "description": "Plain-English cleaning instructions"
                },
                "dirty_data": {
                    "type": "array",
                    "items": {"type": "object"},
                    "description": "The original messy input data"
                },
                "schema_hint": {
                    "type": "object",
                    "description": "Expected column names and types"
                },
                "step_count": {
                    "type": "integer",
                    "description": "How many steps have been taken this episode"
                },
                "done": {
                    "type": "boolean",
                    "description": "Whether the episode is finished"
                },
                "reward": {
                    "type": "number",
                    "description": "Reward from the last action"
                },
                "feedback": {
                    "type": "string",
                    "description": "Grader feedback on last submission"
                },
                "score_breakdown": {
                    "type": "object",
                    "description": "Per-metric partial scores"
                }
            }
        },
        "state": {
            "type": "object",
            "properties": {
                "episode_id": {
                    "type": "string",
                    "description": "Unique episode identifier"
                },
                "step_count": {
                    "type": "integer",
                    "description": "Current step number"
                },
                "task_id": {
                    "type": "integer",
                    "description": "Which task is loaded"
                },
                "max_steps": {
                    "type": "integer",
                    "description": "Maximum steps allowed per episode"
                },
                "best_score": {
                    "type": "number",
                    "description": "Best raw grader score achieved this episode"
                }
            }
        }
    }


@app.get("/metadata", summary="Environment name and description")
def get_metadata() -> Dict[str, Any]:
    """
    Returns environment name and description.
    Required by OpenEnv validator.
    """
    return {
        "name": "data-cleaning-env",
        "version": "1.0.0",
        "description": (
            "An OpenEnv environment where AI agents learn to clean messy "
            "tabular datasets. Simulates a real data engineering task: "
            "normalizing column names, handling missing values, removing "
            "duplicates, type casting, and outlier capping."
        ),
        "tasks": [
            {
                "id": 1,
                "name": "column-cleaner",
                "difficulty": "easy",
                "description": (
                    "Fix malformed column names — convert to lowercase, "
                    "replace spaces with underscores, strip whitespace."
                )
            },
            {
                "id": 2,
                "name": "data-sanitizer",
                "difficulty": "medium",
                "description": (
                    "Handle missing values (fill nulls with medians/defaults), "
                    "remove exact duplicate rows, fill blank strings."
                )
            },
            {
                "id": 3,
                "name": "data-reconstructor",
                "difficulty": "hard",
                "description": (
                    "Full reconstruction: type casting (strings to float/int/bool), "
                    "outlier detection and capping, category normalization and typo fixing."
                )
            }
        ],
        "action_space": {
            "type": "object",
            "fields": {
                "task_id": "integer (1-3)",
                "cleaned_data": "array of objects",
                "metadata": "object (optional)"
            }
        },
        "observation_space": {
            "type": "object",
            "fields": {
                "task_description": "string",
                "dirty_data": "array of objects",
                "schema_hint": "object",
                "feedback": "string",
                "score_breakdown": "object",
                "reward": "float",
                "done": "boolean"
            }
        },
        "reward": {
            "type": "float",
            "range": [0.0, 1.0],
            "description": (
                "raw_score + 0.1*(improvement_bonus) - 0.05*(step_count-1), "
                "clamped to [0, 1]. Provides dense partial-progress signal."
            )
        },
        "episode": {
            "max_steps": 5,
            "termination": "perfect score (>=0.99) OR max steps reached"
        }
    }


# ─────────────────────────────────────────────────────────────────────────────
# Web UI — mount Gradio at /web if ENABLE_WEB_INTERFACE=true
# ─────────────────────────────────────────────────────────────────────────────

import os as _os

if _os.getenv("ENABLE_WEB_INTERFACE", "false").lower() in ("true", "1", "yes"):
    try:
        import gradio as gr
        from openenv.core.env_server.gradio_ui import build_gradio_app
        from openenv.core.env_server.web_interface import (
            WebInterfaceManager,
            load_environment_metadata,
            _extract_action_fields,
            _is_chat_env,
            get_quick_start_markdown,
        )
        from openenv.core.env_server.gradio_theme import (
            OPENENV_GRADIO_CSS,
            OPENENV_GRADIO_THEME,
        )
        from models import DataCleaningAction, DataCleaningObservation

        # Load metadata from README
        _metadata = load_environment_metadata(env, env_name="data-cleaning-env")

        # Create web manager using the same global env instance
        _web_manager = WebInterfaceManager(
            env,
            DataCleaningAction,
            DataCleaningObservation,
            _metadata,
        )

        # Build Gradio blocks
        _action_fields = _extract_action_fields(DataCleaningAction)
        _is_chat = _is_chat_env(DataCleaningAction)
        _quick_start = get_quick_start_markdown(
            _metadata, DataCleaningAction, DataCleaningObservation
        )

        _gradio_blocks = build_gradio_app(
            _web_manager,
            _action_fields,
            _metadata,
            _is_chat,
            title="Data Cleaning Agent Environment",
            quick_start_md=_quick_start,
        )

        # Mount at /web — does not affect any existing endpoints
        app = gr.mount_gradio_app(
            app,
            _gradio_blocks,
            path="/web",
            theme=OPENENV_GRADIO_THEME,
            css=OPENENV_GRADIO_CSS,
        )

        # Redirect root to web UI
        from fastapi.responses import RedirectResponse as _RedirectResponse

        @app.get("/", include_in_schema=False)
        async def _root_redirect():
            return _RedirectResponse(url="/web/")

    except Exception as _e:
        print(f"[WARNING] Web UI could not be mounted: {_e}")
        print("[WARNING] Server will continue without web UI.")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point — required by OpenEnv validator
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    """
    Server entry point.
    Called by: [project.scripts] server = "server.app:main"
    Also called directly when running: python server/app.py
    """
    import uvicorn
    uvicorn.run(
        "server.app:app",
        host="0.0.0.0",
        port=7860,
        workers=1,
    )


if __name__ == "__main__":
    main()