"""
server/app.py
=============
FastAPI HTTP server that wraps the DataCleaningEnvironment.

Endpoints (all required by OpenEnv spec):
  GET  /health  → health check (must return 200)
  POST /reset   → start a new episode
  POST /step    → submit an action (cleaned data)
  GET  /state   → get episode metadata
  GET  /docs    → interactive API docs (auto-generated by FastAPI)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


from typing import Any, Dict

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from models import DataCleaningAction
from server.environment import DataCleaningEnvironment

# ─────────────────────────────────────────────────────────────────────────────
# Application setup
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Data Cleaning Agent Environment",
    description=(
        "An OpenEnv-compliant environment where AI agents learn to clean messy "
        "tabular datasets. Three tasks: column name fixing (easy), missing value "
        "handling (medium), and full data reconstruction (hard)."
    ),
    version="1.0.0",
)

# Allow all origins — required for HuggingFace Spaces and external clients
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# One global environment instance per server process
# (stateful — holds current episode state)
env = DataCleaningEnvironment()


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health", summary="Health check")
def health_check() -> Dict[str, str]:
    """
    Returns 200 OK when the server is running.
    The OpenEnv validator pings this endpoint first.
    """
    return {"status": "healthy"}


@app.post("/reset", summary="Start a new episode")
def reset(
    task_id: int = Query(default=1, ge=1, le=3, description="Task ID: 1=Easy, 2=Medium, 3=Hard")
) -> Dict[str, Any]:
    """
    Start a new episode.

    Query parameter:
        task_id: 1 (column cleaning, easy),
                 2 (missing values + dedup, medium),
                 3 (full reconstruction, hard)

    Returns the initial observation containing the dirty dataset.
    """
    try:
        obs = env.reset(task_id=task_id)
        return {
            "observation": obs.model_dump(),
            "reward": 0.0,
            "done": False,
            "info": {"episode_id": env._episode_id, "task_id": task_id},
        }
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@app.post("/step", summary="Submit cleaned data")
def step(action: DataCleaningAction) -> Dict[str, Any]:
    """
    The agent submits its cleaned version of the dataset.

    Request body (JSON):
        task_id      : int (1, 2, or 3)
        cleaned_data : list of row dicts
        metadata     : dict (optional)

    Returns the grader's evaluation: score, feedback, and next observation.
    """
    try:
        obs, reward, done, info = env.step(action)
        return {
            "observation": obs.model_dump(),
            "reward": reward,
            "done": done,
            "info": info,
        }
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Internal error: {exc}")


@app.get("/state", summary="Get episode state")
def get_state() -> Dict[str, Any]:
    """
    Returns episode-level metadata: episode_id, step_count, task_id, best_score.
    Safe to call before reset() — returns default values if no episode is active.
    """
    return env.state().model_dump()


# ─────────────────────────────────────────────────────────────────────────────
# Entry point — required by OpenEnv validator
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    """
    Server entry point.
    Called by: [project.scripts] server = "server.app:main"
    Also called directly when running: python server/app.py
    """
    import uvicorn
    uvicorn.run(
        "server.app:app",
        host="0.0.0.0",
        port=7860,
        workers=1,
    )


if __name__ == "__main__":
    main()